version: "3"
services:
  backend:
    container_name: cards-backend
    image: cards-backend
    restart: always
    build: .
    ports:
      - "42069:3000"
    depends_on:
      - mongodb
  mongodb:
    container_name: cards-mongodb
    image: mongo
    restart: always
    command: ["-f", "/etc/mongodb.conf"]
    volumes:
      - ./docker/mongo/db.conf:/etc/mongodb.conf
      - ./docker/db:/data/db
    ports:
      - "42070:27017"